### ISSUE TITLE
bad name

### ISSUE THREAD

**Issue by malgreen** [andreasalstrup/chrome-vision#1]

**Comment by danielalexlarsen** [comment]
This issue #1 does not follow project guidelines for issues in general. Please update or remove your issue asap.

**Comment by andreasalstrup** [comment]
We have bigger problems.

**Comment by danielalexlarsen** [comment]
As per our last meeting, we will continue to use the name as it stands. 
If you are still disagreeing on the name, please open a new issue with a more detailed explanation. 
Br, 
Daniel
